---
swagger: 2.0
info:
  title: AwsServerlessExpressApi
paths:
  /:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetIndexFunction.Arn}/invocations
  /{proxy+}:
    get:
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetIndexFunction.Arn}/invocations
  /assets/{proxy+}:
    get:
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: GET
        uri: http://YOUR_UNIQUE_BUCKET_NAME.s3.amazonaws.com/assets/{proxy}
        requestParameters:
          integration.request.path.proxy: method.request.path.proxy
  /client/{proxy+}:
    get:
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: GET
        uri: http://YOUR_UNIQUE_BUCKET_NAME.s3.amazonaws.com/client/{proxy}
        requestParameters:
          integration.request.path.proxy: method.request.path.proxy
  /api/posts:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetPostsFunction.Arn}/invocations
  /api/posts/{slug}:
    get:
      parameters:
        - name: slug
          in: path
          required: true
          type: string
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetPostFunction.Arn}/invocations
